commands = {
	"0-3": "(▀̿Ĺ̯▀̿ ̿)(▀̿Ĺ̯▀̿ ̿) This is the 0-3 police. We have you surrounded. (▀̿Ĺ̯▀̿ ̿)(▀̿Ĺ̯▀̿ ̿)",
	"0-5": "(▀̿Ĺ̯▀̿ ̿) Sir, you are under arrest for fraud. (▀̿Ĺ̯▀̿ ̿)",
	"12p": "Some characters have special properties on some of their color palettes, 12p is usually (Not always) the one reserved for \"the most OP version of the character (healing, infinite super, and so on). This is also known as the 12th Palette.\"",
	"2hu": "Touhou never lets you down! (except when they do)",
	"aal": "ANIMALS AS LEADERS <:PogChamp:230165153646247936>",
	"ae86": "http://i.imgur.com/M5Pt4C9.gifv",
	"alan": "OOOOOOOOOOOOOOOOOOO",
	"ataridragon": "twitchRaid SEIZURE WARNING twitchRaid",
	"atkflan": "<:jacky:258802753348960256> I SWEAR I'M HUMAN",
	"auction": "https://www.youtube.com/watch?v=0JALnMXvf7M",
	"ayu": "UGUUU~!",
	"bagelon": "moderator Your friendly neighborhood moderator is now online SeemsGood",
	"bagelout": "moderator That's a wrap folks CarlSmile I am out for the night. Stay safe, and be kind to each other. Always bet the dream SeemsGood",
	"bailout": "BrokeBack #bailoutlife riPepperonis",
	"balrog": "MY FIGHT MONEYYYYY! BrokeBack",
	"barry": "I like this game",
	"belmondo": "ＷＨＡＴ Ａ ＨＯＲＲＩＢＬＥ ＮＩＧＨＴ ＴＯ ＨＡＶＥ Ａ ＣＵＲＳＥ...",
	"big": "See you in X tier. DatSheffy",
	"bigbear": "SwiftRage READY!?",
	"binary": "MingLee What's biased mean? MingLee",
	"bison": "SoonerLater YES, YES! THIS IS DELICIOUS! SoonerLater",
	"bluemary": "WHERE'S THE FUCKING HITBOX?? DansGame",
	"bluerid": "Time to TURN UP <:Kreygasm:230165466272759808>",
	"bokolose": "WOW! YOU LOSE! BibleThump",
	"bokowin": "BRAVO! YOU WIN! 4Head",
	"bs": "SoonerLater It's only bullshit if I bet against it SoonerLater",
	"bubsy": "CoolCat WHAT COULD PAW-SSIBLY GO WRONG??",
	"buroli": "/me GARBAGE IS STILL GARBAGE!",
	"butthurt": "EVERYONE I BET ON LOSES BibleThump",
	"callsalty1": "#CALLSALTY Bets are down.	subscriber",
	"callsalty2": "#CALLSALTY The stream is down.	subscriber",
	"callsalty3": "#CALLSALTY Payout issue.	subscriber",
	"chelnov": "LET'S GO GO GO NEXT ZONE",
	"chen": "http://i.imgur.com/lyd4CI3.jpg",
	"chip": "WHO GOT THE DIP? TriHard",
	"christmas": "PJSalt Tis the Season to be salty KappaClaus",
	"clara": "EEEEEEEEEEEEE",
	"coffeewolf": "how is this CANON! DansGame",
	"comixzone": "See ya (comix zone voice) B)",
	"crym": "THE RUGAL IS FRUGAL Jebaited",
	"dabone": "A-tier = Garbage Tier DansGame The crossroads of b-tier promotes, s-tier demotes, underpowered 2HUs, and employed descolors. Abandon all hope ye who whale here",
	"danceriot": "└༼ຈل͜ຈ༽┐♫ ┌༼ຈل͜ຈ༽┘ ♪ DANCE RIOT└༼ຈل͜ຈ༽┐♫ └༼ຈل͜ຈ༽┐♫",
	"darkwing": "Let's Bet D A N G E R O U S DatSheffy",
	"davidbell": "CurseLit SPONTANEOUS COMBUSTION CurseLit",
	"dbz": "Always bet on DBZ CarlSmile",
	"dbz2": "Never bet on DBZ Kappa",
	"dbz3": "Always sometimes never bet on DBZ...maybe OneHand",
	"denied": "SwiftRage DENIED!! https://i.imgur.com/rq81TaU.gif",
	"dic": "DEEK Kappa",
	"digglet": "DONATION COMPLETE DatSheffy 7",
	"dio": "You were expecting a real fight, but it was me, Dio!",
	"dio2": "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA",
	"disrespect": "<:PogChamp:230165153646247936> HOLLA HOLLA GET ONE DOLLA",
	"dokuro": "PI PIRU PIRU PIRU PI PIRU PIIIII!! http://i.imgur.com/C5QMCoC.gif",
	"donald": "RAN RAN RUUUUUUU",
	"dooj": "THE DOOJ IZ LOOJ TheThing",
	"doom": "STAY SALTY MY FRIENDS.",
	"dreams": "http://i.imgur.com/g5LoDk8.gif",
	"drew": "SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY SALTY-	owner",
	"duane": "TheRinger DUANE!!!!!! TheRinger",
	"dudley": "Let's fight like gentlemen TriHard",
	"dudley2": "GUTTER TRASH PeoplesChamp",
	"employed": "Jobbing as far as the eye can see",
	"eva": "I got 99 problems but my wealth ain't one BionicBunion",
	"ex8": "Coming in 10 Kappa",
	"exp": "Good thing I only bet $1 Kappa",
	"faq": "Read the FAQ http://www.saltybet.com/about",
	"farts": "WUB WUB WUB WUB WUB",
	"flan": "I still haven't decided on a command 4Head",
	"foxonrainbow": "༼ つ ◕_◕ ༽つ ＰＲＡＩＳＥ ＦＩＳＨ",
	"franco": "OH MY GOOOOOOOOD WutFace",
	"galactus": "I AM A FORCE OF NATURE!",
	"galactus2": "SUBMIT!",
	"ganon": "I just wonder what Gannon's up to Kappa",
	"garner": "HELPU ME! BibleThump",
	"geese": "THE GEESE IS LEESE SwiftRage",
	"geese2": "I HAVE BEEN WAITING FOR YOU SoonerLater",
	"geese3": "PREDICTABO!",
	"ghetto": "SMOKE WEED EVERY DAY!",
	"googoo": "googoo detected FrankerZ",
	"gustab": "DREAM CANCEL.",
	"guts": "SoBayed Takes guts to bet on Guts SoBayed",
	"halon": "GivePLZ riPepperonis CurseLit CHESTO IS BESTO! CurseLit riPepperonis TakeNRG",
	"help": "Place your bets at http://www.saltybet.com!",
	"highlights": "Highlights available at http://www.youtube.com/saltyhighlights",
	"himan": "HE HE HE HE HAWWWWWWWWW",
	"hinata": "HeyGuys .....Naruto kun!",
	"hitbox": "WutFace THESE HITBOXES!",
	"hobgoblin": "Name's Hobgoblin, and you're right on time... For your funeral",
	"hug": "/me hugged [touser] ([count] hugs have been given)",
	"infiltration": "DOWNLOAD COMPLETE <:jacky:258802753348960256>",
	"info": "Order of Modes: 100 matchmaking fights, tier specified tournament, and then 25 exhibitions. <:PogChamp:230165153646247936>",
	"jmoney": "OpieOP Where did all my salt go?",
	"job": "Welp, time to go to work OpieOP",
	"jobber": "http://i.imgur.com/Wzkmtyj.gif",
	"joblike": "Super Fighting Robot................ MegaMan",
	"juggernaut": "I'm gonna kill him, I'm gonna have consensual sex in the missionary position with him, I'm gonna eat his fuckin' costume, just wait",
	"karin": "PMSTwin YIPYIPYIPYIPYIPYIPYIPYIPYIP",
	"keion": "REMEMBER THE FALLEN BibleThump 7",
	"kenshiro": "ATATATATATATATATATATAT",
	"kenwins": "ヽ༼ຈل͜ຈ༽ﾉ FIX SB OR RIOT ヽ༼ຈل͜ຈ༽ﾉ",
	"kestel": "BURY ME WITH MY MONEY 4Head",
	"kirby": "To travel far beyond is just my master plan",
	"koolaid": "OH YEAAAAAH <:Kreygasm:230165466272759808>",
	"larpi": "SwiftRage Don't Hurt The Lolis",
	"lavos": "SKREEEEEEEREEEEEEEEE",
	"leese": "SwiftRage THE LEESE IS GEESE",
	"leftturn": "Drop your salt! This is a robbery MVGame",
	"lewd": "http://i.imgur.com/SyRFPmy.gif",
	"lf2": "SwiftRage Lets drink some booze! SwiftRage",
	"lilb": "KevinTurtle KETCHUP BLUKEN, HADOUKEN. THANK YOU BASED GOD!",
	"lolilich": "2hu is the best VoHiYo",
	"longshot": "The better fighter won! <:Kreygasm:230165466272759808>",
	"lottery": "<:PogChamp:230165153646247936> You have a chance to win 100,000 salty bucks! Type IMANIDIOT in chat to enter! <:PogChamp:230165153646247936>	moderator",
	"m0nk": "Time to get that reverse perfect SoBayed",
	"magknegrow": "R.I.P in piece BibleThump",
	"mami": "http://i.imgur.com/kVyQm0T.gif",
	"mavrick": "Always never sometimes on occasion trust Mavrick",
	"mines": "ᕕ( ᐛ )ᕗ OFF TO THE SALT MINES ᕕ( ᐛ )ᕗ",
	"mod": "/me #MODEVERYONE",
	"money": "4Head There goes my salt.",
	"moosecrap": "4Head I REGRET NOTHING!!",
	"moot": "Odds? What odds? CoolStoryBob",
	"mudman": "SEE YOU IN P-TIER MVGame",
	"mugen": "M.U.G.E.N is a fighting game engine. Content is created by the community, and thousands of fighters, both original and from popular fiction, have been created.",
	"muscle": "NUMBA WAAAAAAAAAN",
	"museli": "VoHiYo Oh hello there I'm the quiet, Waifu Wars playing, no tournament winning, poor life having guy that just wants you to enjoy themselves. CarlSmile",
	"neozekrom": "DESTROY US ALL! DESTROY US ALL!",
	"newageking": "WINNER WINNER CHICKEN DINNER tbChickenBiscuit",
	"news": "Read the Salt Mines Weekly here! http://phazonupsilon.imgur.com/",
	"newtier": "New Tier features new characters that are currently being implemented. New characters will fight each other to measure their performance to tier them in our regular tiers. Tournaments and exhibitons continue as usual. You can't request NEW characters until they are tiered. <:PogChamp:230165153646247936>",
	"nightcrew": "Night Crew is best crew SeemsGood",
	"nitori": "Nyuuuuuu",
	"obama": "THANKS OBAMA! SoBayed http://i.imgur.com/ZOlaTCK.gif",
	"omanyte": "PRAISE THE HELIX!",
	"onslaught": "THE DREAM IS DEAD!",
	"orochi": "ARIEN ARIEN!!",
	"orochi2": "ARIEN ARIEN!! ARIEN ARIEN!! ARIEN ARIEN!! ARIEN ARIEN!! ARIEN ARIEN!! ARIEN ARIEN!! ARIEN ARIEN!!",
	"orochigoku": "Greed never pays! https://www.youtube.com/watch?v=XILhYhxMTEk",
	"overlord": "<:jacky:258802753348960256> AT LAST, I'VE FINALLY TASTED VICTOR-",
	"pendaflex": "This is so free ¯\_(ツ)_/¯",
	"perfect": "I AM A PERFECT SOLDIER DatSheffy",
	"potato": "So much hy- ResidentSleeper",
	"potatomatch": "RING RING RING RING RING RING RING, *POTATO MATCH*! https://soundcloud.com/anime_sonicmega/saltybet-classics-potato",
	"ptm": "POWDERED T O A S T MAN!",
	"rakeel": "upset Life EZ Life Jebaited",
	"real": "<:PogChamp:230165153646247936> FINAL ROUND HYPE! <:PogChamp:230165153646247936>",
	"realdoom": "FailFish FUCK! FailFish",
	"ride": "ヽ༼ຈل͜ຈ༽ﾉ I WANNA TAKE U 4 A RIDE ヽ༼ຈل͜ຈ༽ﾉ",
	"rony": "MY ODDS! BibleThump",
	"rounds": "Exhibitions, X Tier and P tier matchmaking is BO3. Normal matchmaking and tournaments is BO5. Tournament finals is BO9.",
	"sadclaps": "DREAMS...DON'T DIE",
	"sadclaps2": "DON'T ANYBODY MOVE... I DROPPED MY CONTACT LENS.",
	"sakuya": "ヽ༼ຈل͜ຈ༽ﾉ GET FISTED ヽ༼ຈل͜ຈ༽ﾉ",
	"salthand": "my odds, my odds, MY ODDS, MY ODDS BibleThump https://soundcloud.com/anime_sonicmega/saltybet-classics-salt-hand	",
	"saltyjohto": "Salty Johto by ShaydoGaming https://soundcloud.com/blahernandez/salty-johto",
	"saltyoprah": "YOU GET A COMMAND AND YOU GET A COMMAND EVERYBODY GETS A COMMAND",
	"sandstorm": "/me ༼ つ ◕_◕ ༽つ DUDUDUDUDUDUDUDUDUDU <(◕_◕< )",
	"sanic": "OC DONUT STEEL DxCat",
	"scam": "http://i.imgur.com/FhsxyfM.gif",
	"scam1": "http://i.imgur.com/wio5VrS.gifv",
	"scam10": "http://i.imgur.com/mEYzpbE.gifv",
	"scam11": "http://i.imgur.com/Bf3LmUu.gifv",
	"scam12": "http://i.imgur.com/G6UeTIy.gifv",
	"scam13": "http://i.imgur.com/tEIiFQb.gifv",
	"scam14": "http://i.imgur.com/h4tpcfx.gifv",
	"scam15": "http://i.imgur.com/osckjF4.gifv",
	"scam16": "http://i.imgur.com/7TqqLX0.gifv",
	"scam17": "http://i.imgur.com/H7XxvxB.gifv",
	"scam18": "http://i.imgur.com/guuHKcP.gifv",
	"scam19": "https://clips.twitch.tv/TameCogentGazelleDoritosChip",
	"scam2": "http://i.imgur.com/wxk0pMv.gif",
	"scam3": "http://i.imgur.com/Q2Mupkc.gif",
	"scam4": "http://i.minus.com/iFzRReS23QDAF.gif",
	"scam5": "http://i.imgur.com/QK1ONVU.gifv",
	"scam6": "http://i.imgur.com/wNI4OGJ.gifv",
	"scam7": "http://i.imgur.com/HuhDL5I.gifv",
	"scam8": "http://i.imgur.com/tUcHoSV.gifv",
	"scam9": "http://i.imgur.com/38KMjTC.gif",
	"shaq": "ALL I DO IS WIN WIN TriHard",
	"shia": "SwiftRage DONT LET YOUR DREAMS BE DREAMS SwiftRage",
	"shia1": "SwiftRage JUST DO IT! SwiftRage",
	"shia2": "SwiftRage NOTHING IS IMPOSSIBLE! SwiftRage Just DO IT! SwiftRage",
	"shia3": "SwiftRage MAKE YOUR DREAMS COME TRUE! SwiftRage",
	"skip": "TURN OFF THAT FIGHT! SwiftRage",
	"sleep": "JUST ONE MORE BET ResidentSleeper",
	"sonicmega": "TIME TO MUTE",
	"ssjpotato": "EYAAAAAAAAH",
	"sun": "☼ PRAISE THE SUN!! \ [ T ] / ☼",
	"sunra777": "EVO 2016 SALTYBET CHAMPION!",
	"supersaltybetting": "https://soundcloud.com/anime_sonicmega/super-salty-betting EVERYBODY <:Kreygasm:230165466272759808>",
	"surfer": "You are already dead. SoonerLater",
	"sword": "ALWAYS BET SWORD SwiftRage",
	"sword2": "because there was no sword2 Kappa",
	"talbain": "RRRRRRRRRRRRRRRRRRR",
	"teex": "<3 Long live Konpaku Corp, long live the waifu loyalty! <3 | http://i.imgur.com/QKzQBNv.gif",
	"terms": "SaltyBet Glossary/Dictionary: https://docs.google.com/document/d/1QVo87iaWeWNb8JknOg6CRITXk81ZYGpV-NIQgFv16DA/",
	"theford": "GOTT EMMMMMM SoonerLater",
	"thma": "SwiftRage The School of the Undefeated of the East! The Winds of the King! Zenshin! Keiretsu! Tenpa kyoran! Look, the East is Burning Red! 東方不敗!!",
	"thunder": "SwiftRage THUNDAAAAAAAAAAAH",
	"tien": "SwiftRage I AM NOT GONNA BOW DOWN TO THE SAIYAN JERKS! SwiftRage",
	"tiggle": "wtf is Scotland",
	"tizoc": "SwiftRage BIIIIIIIIIIIIIIIIIIIG! WHOOOOOOOOOOOORE!! SwiftRage",
	"tmnt": "MVGame LET'S KICK SHELL MVGame",
	"tmnt2": "BrokeBack SHELL SHOCKED BrokeBack",
	"trap": "The outcome is obvious, I'm just betting wrong on purpose BabyRage",
	"truthmoon": "I Dont Always Win But When I Do VoHiYo I ALL IN VoHiYo",
	"twitter": "Follow Salty Bet on Twitter for the latest updates! https://twitter.com/SaltyBet",
	"upset": "Knew that was going to happen Kappa",
	"vegeta": "I FEEL GREAT 4Head",
	"veku": "PermaSmug Potato is my middle name",
	"venom": "DELETED. DansGame",
	"vergil": "WHERE'S YOUR MOTIVATION? SoonerLater",
	"vile": "It is not the waifu who has betrayed me. It is me who has betrayed the waifu. BibleThump",
	"vitioff": "Your actions, and your action alone, determines your worth.	moderator",
	"vition": "Bring me the Husbandos	moderator",
	"vitirage": "SwiftRage KILL HIS DICK SwiftRage",
	"wafiu": "MY WAIFUUUU! <:Kreygasm:230165466272759808> BibleThump",
	"waifu": "MY WAIFUUUU! <:Kreygasm:230165466272759808> BibleThump",
	"waifuwars": "Join the beta here: http://www.saltybet.com/waifuwars",
	"wball": "The better fighter lost FailFish",
	"xtier": "ThunBeast It's a tornado of fireworks! ThunBeast",
	"yuri": "AAAAAAAAAAAAAAAAAA",
	"zangrief": "THE RUSSIAN SKIES ARE SAD THIS NIGHT PipeHype",
	"zuranthus": "that's right, i'm a dirty dirty scoundrel EleGiggle"
}